services:
  - type: web
    name: vidtoscore-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    buildFilter:
      paths:
        - backend/**
        - render.yaml
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: YOUTUBE_COOKIES
        value: "" # Add your Netscape formatted cookies here if you get bot errors
